var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.findInternal=function(a,c,b){a instanceof String&&(a=String(a));for(var d=a.length,e=0;e<d;e++){var f=a[e];if(c.call(b,f,e,a))return{i:e,v:f}}return{i:-1,v:void 0}};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;
$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,c,b){a!=Array.prototype&&a!=Object.prototype&&(a[c]=b.value)};$jscomp.getGlobal=function(a){return"undefined"!=typeof window&&window===a?a:"undefined"!=typeof global&&null!=global?global:a};$jscomp.global=$jscomp.getGlobal(this);
$jscomp.polyfill=function(a,c,b,d){if(c){b=$jscomp.global;a=a.split(".");for(d=0;d<a.length-1;d++){var e=a[d];e in b||(b[e]={});b=b[e]}a=a[a.length-1];d=b[a];c=c(d);c!=d&&null!=c&&$jscomp.defineProperty(b,a,{configurable:!0,writable:!0,value:c})}};$jscomp.polyfill("Array.prototype.find",function(a){return a?a:function(a,b){return $jscomp.findInternal(this,a,b).v}},"es6","es3");
$.widget("mc.clock",$.mc.master,{_touch:2,options:{groupVisible:1,hashWidOpts:"angleType,hour,min,sec,realTime",fracType:"min",fracSimp:!1,draggable:!0,protractor:!1,autoProtr:!1,digiType:"_12",rows:9,cols:12,mode:"Time",ang:50,hour:1,min:0,sec:0,addHours:0,addMins:0,_hide_frac1:!1,_hide_frac2:!1,_hide_perc:!0,_color_grid:"rgba(100,100,255,0.1)",load:[{type:"analogueclock",pos:{x:4.5,y:4.5,w:9,h:9},opts:{rows:"9",cols:"9",realTime:!1}},{type:"protractor",pos:{x:4.5,y:4.5,w:9,h:9},opts:{r:3,rows:"9",
cols:"9"}}],controls:[{pos:{x:10,y:.5,w:4,h:1,fs:.9},type:"html",cl:"notranslate",css:{borderRadius:"0.25em",background:"#000",color:"lime",fontFamily:"Courier"},opt:"digi"},{pos:{x:9.5,y:1.5,w:1,h:1,pad:.05},type:"button",opt:"_12",label:12},{pos:{x:10.5,y:1.5,w:1,h:1,pad:.05},type:"button",opt:"_24",label:24},{pos:{x:11.5,y:1.5,w:1,h:1,pad:.05},type:"button",opt:"_off",label:"off"},{pos:{x:9.75,y:4.5,w:1.5,h:1,fs:.6,pad:.2},type:"boolean",opt:"protractor",icon:"icons/protractor",group:2},{pos:{x:11.25,
y:2.5,w:1.5,h:1,fs:.6,pad:.1},type:"button",opt:"rand",icon:"icons/dice"},{pos:{x:10.5,y:3.5,w:3,h:1,fs:.7,pad:0},type:"select",vals:"Time",opt:"mode",label:"Mode"},{pos:{x:10.5,y:5.5,w:3,h:1,fs:.7,pad:0},type:"input",attr:{readonly:!0},label:"hours",opt:"addHours",group:1},{pos:{x:10.5,y:6.5,w:3,h:1,fs:.7,pad:0},type:"input",attr:{readonly:!0},label:"minutes",opt:"addMins",group:1},{pos:{x:10.5,y:7.5,w:3,h:1,fs:.7,pad:.1},type:"button",label:"Reset",opt:"reset",call:"resetHM",
group:1},{pos:{x:11.25,y:4.5,w:1.5,h:1,fs:.9,pad:.2},type:"boolean",opt:"autoProtr",label:"auto",group:2},{pos:{x:10.5,y:8.5,w:3,h:1,fs:.65,pad:0},type:"select",opt:"angleType",vals:"seconds,hour to min,min to hour",group:2},{widId:"analogueclock1",pos:{x:10.5,y:5.5,w:3,h:1,fs:.9,pad:.2},type:"boolean",opt:"thinHands",label:"Thin Hands",group:2},{pos:{x:9.75,y:7.5,w:1.5,h:1,fs:.9,pad:.2},type:"boolean",opt:"showAng",label:"Angle",group:2},{pos:{x:11.25,y:7.5,w:1.5,h:1,fs:.9,pad:.2},type:"boolean",
opt:"showArc",label:"Arc",group:2},{widId:"analogueclock1",pos:{x:9.75,y:2.5,w:1.5,h:1,fs:.7,pad:.1},type:"boolean",opt:"realTime",label:"Real Time"},{pos:{x:10.5,y:6.5,w:3,h:1,fs:.9,pad:.2},type:"boolean",opt:"snapMin",label:"Snap Mins",group:2},{pos:{x:9.75,y:5.5,w:1.5,h:1,fs:.8,pad:.2},type:"select",vals:"none,auto,60,30,20,15,12,10,5,4,3,2",opt:"fracGrads",group:4},{pos:{x:10.5,y:7,w:3,h:2,fs:.3},type:"html",css:{textAlign:"center"},group:4,val:"<p>=</p>",cl:"ui-widget-content"},{widId:"clock1",
pos:{x:9.75,y:7,w:1.5,h:2,fs:.9},type:"html",opt:"frac1",css:{textAlign:"center"},hide:"?",group:4},{pos:{x:11.25,y:7,w:1.5,h:2,fs:.9},type:"html",opt:"frac2",css:{textAlign:"center"},group:4,hide:"?"},{pos:{x:10.5,y:8.5,w:3,h:1,fs:.8,pad:.1},type:"html",opt:"perc",val:"<span>",css:{textAlign:"center"},cl:"ui-widget-content",group:4,hide:"?"},{pos:{x:10.5,y:4.5,w:1.5,h:1,fs:.9,pad:.2},type:"boolean",label:"simple",opt:"fracSimp",group:4},{widId:"analogueclock1",pos:{x:10.5,y:8,w:3,h:2,fs:.7,pad:0},
type:"colPicker",opt:"cpick",group:3},{pos:{x:9.75,y:4.25,w:1.5,h:.5,pad:.05},type:"select",vals:"round,butt,square",opt:"gradLineCap",group:3},{pos:{x:11.25,y:4.25,w:1.5,h:.5,pad:.05},type:"select",vals:"round,butt,square",opt:"handLineCap",group:3},{pos:{x:11.25,y:4.75,w:1.5,h:.5,fs:.9,pad:.1},type:"input",attr:{type:"number",min:.01,max:.5,step:.01},opt:"_sqr_minGradWidth",group:3},{pos:{x:9.75,y:4.75,w:1.5,h:.5,fs:.9,pad:.1},type:"input",attr:{type:"number",min:.01,max:.5,step:.01},opt:"_sqr_majGradWidth",
group:3},{pos:{x:11.5,y:5.25,w:1,h:.5,fs:.5,pad:.05},type:"color",opt:"_color_fracFill",label:"fraction",group:3},{pos:{x:10.5,y:5.25,w:1,h:.5,fs:.5,pad:.05},type:"color",opt:"_color_fracGrad",label:"fraction dividers",group:3},{pos:{x:9.5,y:5.75,w:1,h:.5,fs:.5,pad:.05},type:"color",opt:"_color_nos",label:"numbers",group:3},{pos:{x:10.5,y:5.75,w:1,h:.5,fs:.5,pad:.05},type:"color",opt:"_color_grad",label:"graduations",group:3},{pos:{x:11.5,y:5.75,w:1,h:.5,fs:.5,pad:.05},type:"color",opt:"_color_back",
label:"background",group:3},{pos:{x:9.5,y:6.25,w:1,h:.5,fs:.5,pad:.05},type:"color",opt:"_color_rim",label:"rim",group:3},{pos:{x:10.5,y:6.25,w:1,h:.5,fs:.5,pad:.05},type:"color",opt:"_color_gradback",label:"outer",group:3},{pos:{x:11.5,y:6.25,w:1,h:.5,fs:.5,pad:.05},type:"color",opt:"_color_face",label:"clock face",group:3},{pos:{x:9.5,y:6.75,w:1,h:.5,fs:.5,pad:.05},type:"color",opt:"_color_sec",label:"second hand",group:3},{pos:{x:10.5,y:6.75,w:1,h:.5,fs:.5,pad:.05},type:"color",opt:"_color_min",
label:"minute hand",group:3},{pos:{x:11.5,y:6.75,w:1,h:.5,fs:.5,pad:.05},type:"color",opt:"_color_hour",label:"hour hand",group:3}]},_start:function(){var a=this,c=a.options,b=a._ob;a.$digi=a._get$Ctrl("digi").attr("translate","no");$(".ui-widget,.ui-widget-content").add(a.$add).css("fontFamily","comic sans ms,ChalkboardSE-Regular");a._setGroupVisible();b.aniClock=a.widById("analogueclock1");b.protractor=a.widById("protractor1");a.resetHM();a._get$Ctrl("angleType").find("select").val(b.aniClock.options.angleType).find("option").each(function(a,
b){return b.innerHTML=b.innerHTML+" "+bb.getSymb(8635)});a._update("protractor",c.protractor);b.$fr=a._get$Ctrl("frac1,frac2").append("<div class=mc-frac><span></span><span></span></div>");b.$pe=a._get$Ctrl("perc").find("span");b.aniClock.element.on("analogueclockaniend analogueclocktick analogueclockchange",function(b,c){a._handler(b,c)});a._update(c.digiType)},resetHM:function(){this.startTime=this._ob.aniClock.date;this.startTime.setSeconds(0);this._refAddTimes()},_refAddTimes:function(){var a=
this.options,c=new Date(6E4*Math.round((this._ob.aniClock.date.getTime()-this.startTime.getTime())/6E4));a.addMins=c.getMinutes();a.addHours=c.getUTCHours();this.refreshCtrls("addMins,addHours")},_handler:function(a,c){var b=this._ob;a=this.options;this._updateDigi();c.frac&&($.each(c.frac,function(a,c){b.$fr.eq(a).find("span").eq(0).text(c[0]).end().eq(1).text(c[1]);0===a&&b.$pe.text(1*(c[0]/c[1]*100).toFixed(2)+" %")}),this.refreshCtrls("perc"));"Time"===a.mode&&this._refAddTimes();if(a.protractor&&
a.autoProtr&&null!==c.angle){switch(c.angleType){case "seconds":var d=180>c.angle?-Math.PI/2:Math.PI/2;break;case "min to hour":case "hour to min":d=180>c.angle?Math.PI+c.arcProps.arcSt:Math.PI+c.arcProps.arcEnd}b.protractor.options.x=4.5;b.protractor.options.y=4.5;b.protractor.options.clockwise=!1;b.protractor.option({ang:d})}},_updateDigi:function(){var a=$.inArray(this.options.digiType,["_12","_24","_off"]),c=this._ob.aniClock.getDigitArr(1===a),b="";this.showHide(this.$digi,2!==a);for(a=0;a<c.length;a++)b+=
"<span style='"+(3===a?"vertical-align:top;":"")+"text-align:right;width:"+[30,30,10,10][a]+"%;font-size:"+(1<a?.5:1)+"em;display:inline-block'>"+c[a]+"</span>",0===a&&(b+=":");this.$digi.html(b)},_update:function(a,c){var b=this._ob,d=this.options,e=b.aniClock,f=e.options;switch(a){case "_12":case "_24":case "_off":return d.digiType=a,this._updateDigi();case "angleType":e.option(a,c);break;case "rand":e.option("realTime",!1);this.refreshCtrls("realTime");b.aniClock.animate({hour:bb.rand(0,23,1)+
48,min:bb.rand(0,59,1)+120,sec:"Fraction"===d.mode?0:120+bb.rand(0,59,1)},{duration:1500},!0);break;case "protractor":b.protractor[!0===c?"show":"hide"]();break;case "autoProtr":d.protractor&&e._trigEvent("change");break;case "fracSimp":a=["grad","rim","sec","hour"];if(c){var g={};b.st={};$.each(a,function(a,c){a="_color_"+c;b.st[a]=f[a];g[a]="rgba(0,0,0,0)"});e.option(g)}else e.option(b.st),b.st=null;break;case "mode":this._setGroupVisible(1+$.inArray(c,["Time"]));var h=
a=!1,k=!0;switch(c){case "Fraction":a=!0;f.snapMin=!0;this.refreshCtrls("snapMin");b.st&&(e.option(b.st),b.st=null);break;case "Angles":h=!0,k=!1}f.snapMin=k;this.refreshCtrls("snapMin");f.showArc=h;this.refreshCtrls("showArc");f.sweepMin=!a;e.option("fraction",a?d.fracType:null)}f.handLengths[2]="Angles"===d.mode&&"seconds"!==f.angleType?0:.8;this._paint()}});
